CREATE TABLE `factura` (
  `idCliente` varchar(45) DEFAULT NULL,
  `nombre` varchar(45) DEFAULT NULL,
  `apellido` varchar(45) DEFAULT NULL,
  `telefono` varchar(45) DEFAULT NULL,
  `email` varchar(45) DEFAULT NULL,
  `ciudad` blob,
  `pais` blob,
  `idFactura` varchar(45) DEFAULT NULL,
  `fechaFactura` varchar(45) DEFAULT NULL,
  `idProducto` varchar(45) DEFAULT NULL,
  `nombreProducto` varchar(45) DEFAULT NULL,
  `cantidad` varchar(45) DEFAULT NULL,
  `precioUnitario` varchar(45) DEFAULT NULL,
  `precioTotal` varchar(45) DEFAULT NULL,
  `idCategoria` varchar(45) DEFAULT NULL,
  `nombreCategoria` varchar(45) DEFAULT NULL,
  `descripcionCategoria` blob,
  `idEmpleado` varchar(45) DEFAULT NULL,
  `nombreEmpleado` varchar(45) DEFAULT NULL,
  `apellidoEmpleado` varchar(45) DEFAULT NULL,
  `fechaIngreso` varchar(45) DEFAULT NULL,
  `fechaNacimiento` varchar(45) DEFAULT NULL,
  `sexo` varchar(45) DEFAULT NULL,
  `salario` varchar(45) DEFAULT NULL,
  `idDepartamento` varchar(45) DEFAULT NULL,
  `nombreDepartamento` blob
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;